var clsPeliculas = function(titulo,afiche,refmovie,libro,refbook, duracion,director,guion, productor, estudio, compositor, m, sinopsis)
{
	this.titulo =titulo;
	this.afiche = afiche;
	this.refmovie = refmovie;
	this.libro = libro;
	this.refbook = refbook;
	this.sinopsis = sinopsis;
	this.duracion = duracion;
	this.director = director;
	this.guion = guion;
	this.productor = productor;
	this.estudio = estudio;
	this.compositor = compositor;
	this.m = m;
}

var film = new Array();

film[0] = new clsPeliculas("Harry Potter y la piedra filosofal","img/peliculas/uno.jpg","movie.html?m=1", "img/inicio/1.jpg","book.html?b=1", "152 minutos", "Chirs Colombus", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "John Williams", "1", "Estrenada el 16 de noviembre de 2001, en Londres, Harry Potter y la piedra filosofal fue un enorme éxito en taquilla.<br><br>Harry Potter se entera en su undécimo cumpleaños de que es el hijo huérfano de dos magos y de que posee poderes mágicos propios. En el Colegio Hogwarts de Magia y Hechicería aprende el deporte de altos vuelos del Quidditch y juega una emocionante partida de ajedrez “en vivo”, cuando va a enfrentarse al Mago Oscuro, que está decidido a destruirlo.");
film[1] = new clsPeliculas("Harry Potter y la cámara secreta","img/peliculas/dos.jpg","movie.html?m=2", "img/inicio/2.jpg","book.html?b=2", "161 minutos", "Chirs Colombus", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "John Williams", "2", "Harry Potter y la cámara secreta se estrenó en el Reino Unido el 15 de noviembre de 2002. El éxito de la película estaba asegurado gracias al creciente número de admiradores que comenzaban a conocer las historias.<br><br>Los coches vuelan, los árboles devuelven los golpes y un misterioso elfo doméstico llega para advertir a Harry Potter, al comienzo de su segundo curso en Hogwarts. Peligros y aventuras aguardan cuando unas palabras sangrientas anuncian en una pared: “La cámara secreta ha sido abierta”. Para salvar a Hogwarts, Harry, Ron y Hermione necesitarán todas sus habilidades mágicas y todo su valor.");
film[2] = new clsPeliculas("Harry Potter y el prisionero de Azkaban","img/peliculas/tres.jpg","movie.html?m=3", "img/inicio/3.jpg","book.html?b=3", "141 minutos", "Alfonso Cuarón", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "John Williams", "3", "Harry Potter y el prisionero de Azkabane estrenó en el Reino Unido el 31 de mayo de 2004.<br><br>En su tercer curso en Hogwarts, Harry, Ron y Hermione conocen al prisionero fugado Sirius Black y aprenden a controlar un hipogrifo –mitad caballo, mitad águila; a repeler a los boggarts de forma cambiante y a dominar el arte de la adivinación. Harry también debe soportar a los dementores que absorben las almas, a ser más listo que un peligroso hombre lobo y a hacer frente a la verdad sobre Sirius y su relación con Harry y sus padres.");
film[3] = new clsPeliculas("Harry Potter y el cáliz de fuego","img/peliculas/cuatro.jpg","movie.html?m=4", "img/inicio/4.jpg","book.html?b=4", "157 minutos", "Mike Newell", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "Patrick Doyle", "4", "Esta es la cuarta película de la serie de Harry Potter. Se estrenó el 18 de noviembre de 2005 en el Reino Unido.<br><br>Harry Potter es misteriosamente apuntado al Torneo de los Tres Magos, un agotador concurso entre tres colegios de magia, en el que se enfrenta a un dragón, a demonios acuáticos y a un laberinto encantado, solo para terminar al alcance de Lord Voldemort. Todo cambia cuando Harry, Ron y Hermione dejan atrás para siempre su niñez y se enfrentan a retos más allá de su propia imaginación.");
film[4] = new clsPeliculas("Harry Potter y la Orden del Fénix","img/peliculas/cinco.jpg","movie.html?m=5", "img/inicio/5.jpg","book.html?b=5", "138 minutos", "David Yates", "Michael Goldenberg", "David Heyman", "Warner Bros. Pictures", "Nicholas Hooper", "5", "Harry Potter y la Orden del Fénix se estrenó el 12 de julio de 2007.<br><br>¡Comienza la rebelión! Lord Voldemort ha vuelto, pero el Ministerio de Magia intenta mantener oculta la verdad –incluido el nombramiento en Hogwarts de un nuevo y sediento de poder catedrático de Defensa contra las artes oscuras. Ron y Hermione convencen a Harry para que secretamente adiestre a los alumnos para la guerra de magia que se avecina. Les aguarda un terrorífico enfrentamiento entre el bien y el mal…");
film[5] = new clsPeliculas("Harry Potter y el misterio del príncipe","img/peliculas/seis.jpg","movie.html?m=6", "img/inicio/6.jpg","book.html?b=6", "153 minutos", "David Yates", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "Nicholas Hooper", "6", "Harry Potter y el misterio del príncipe se estrenó el 15 de julio de 2009.<br><br>Conforme Lord Voldemort aumenta su control sobre los mundos de los muggles y de la magia, Dumbledore está cada vez más decidido a preparar a Harry para la batalla que se avecina. No obstante, incluso pese a la amenaza del enfrentamiento, el romance surge entre Harry, Ron, Hermione y sus compañeros de clase. El amor se respira en el aire, pero se avecina el peligro y es posible que Hogwarts nunca vuelva a ser igual que antes.");
film[6] = new clsPeliculas("Harry Potter y las reliquias de la muerte I","img/peliculas/siete.jpg","movie.html?m=7", "img/inicio/7.jpg","book.html?b=7", "146 minutos", "David Yates", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "Alexandre Desplat", "7", "Harry Potter y las reliquias de la muerte, Parte 1 se estrenó en el Reino Unido y los Estados Unidos el 19 de noviembre de 2010.<br><br>Harry, Ron y Hermione se proponen encontrar y destruir el secreto del poder de Voldemort –los Horcruxes. Por su cuenta y como fugitivos, los tres deben confiar los unos en los otros más que nunca… pero las fuerzas oscuras amenazan con separarlos.");
film[7] = new clsPeliculas("Harry Potter y las reliquias de la muerte II","img/peliculas/ocho.jpg","movie.html?m=8", "img/inicio/7.jpg","book.html?b=7", "130 minutos", "David Yates", "Steve Kloves", "David Heyman", "Warner Bros. Pictures", "Alexandre Desplat", "8", "Harry Potter y las reliquias de la muerte, Parte 2 se estrenó en el Reino Unido y los Estados Unidos el 15 de julio de 2011. Obtuvo los mejores resultados de todos los tiempos registrados en taquilla el primer fin de semana de estreno, tanto a nivel nacional como internacional, y actualmente es la tercera película más taquillera en todo el mundo.<br><br>En este épico final, la batalla entre las fuerzas del bien y del mal dentro del mundo de la magia se convierte en una guerra total. Nunca ha habido tanto en juego, por lo que nadie está seguro. Pero es Harry quien será llamado a hacer el máximo sacrificio conforme se vaya acercando al enfrentamiento culminante con Lord Voldemort.");