
var libro = [
	{"referencia":"book.html?b=1","imagen":"img/inicio/1.jpg", "titulo":"Harry Potter y la piedra filosofal", 
	"capitulos":"1.El niño que vivió<br>2.El vidrio que se desvaneció<br>3.Las cartas de nadie<br>4.El guardián de las llaves<br>5.El callejón Diagon<br>6.El viaje desde el andén nueve y tres cuartos<br>7.El sombrero seleccionador<br>8.El profesor de pociones<br>9.El duelo a medianoche<br>10.Halloween<br>11.Quidditch<br>12.El espejo de Oesed<br>13.Nicolás Flamel<br>14.Norberto, el ridgeback noruego<br>15.El bosque prohibido<br>16.A través de la trampilla<br>17.El hombre con dos caras",
	"argumento":"El primer libro de J.K. Rowling, Harry Potter y la piedra filosofal, fue publicado el 26 de junio de 1997.<br><br>Harry Potter cree que es un chico corriente. Vive con su tío Vernon, su tía Petunia y su primo Dudley, que le obligan a dormir en un armario debajo de las escaleras.  Harry comienza a recibir unas misteriosas cartas y su vida cambia para siempre. Un hombretón gigantesco con ojos de escarabajo se lo lleva volando y lo matricula en el Colegio Hogwarts de Magia y Hechicería. El motivo: ¡Harry Potter es un mago!",
	"b":"1"
	}, //fin libro 1

	{"referencia":"book.html?b=2","imagen":"img/inicio/2.jpg", "titulo":"Harry Potter y la cámara secreta",
	"capitulos":"1.El peor cumpleaños<br>2.La advertencia de Dobby<br>3.La Madriguera<br>4.En Flourish y Blotts<br>5.El sauce boxeador<br>6.Gilderoy Lockhart<br>7.Los «sangre sucia» y una voz misteriosa<br>8.El cumpleaños de muerte<br>9.La inscripción en el muro<br>10.La «bludger» loca<br>11.El club de duelo<br>12.La poción «multijugos»<br>13.El diario secretísimo<br>14.Cornelius Fudge<br>15.Aragog<br>16.La Cámara de los Secretos<br>17.El heredero de Slytherin<br>18.La recompensa de Dobby",
	"argumento":"El Segundo título de la serie, Harry Potter y la cámara secreta, fue publicado el 2 de julio de 1998. Se mantuvo en el puesto número uno de las listas de libros más vendidos de tapa dura para adultos durante el primer mes tras su publicación.<br><br>Harry Potter es un mago. Está en su segundo curso del  Colegio Hogwarts de Magia y Hechicería. Los tres amigos, Harry, Ron y Hermione, pronto se ven inmersos en la rutina diaria de Pociones, Herbología, Defensa contra las artes oscuras y Quidditch. Luego comienzan a suceder cosas misteriosas y espeluznantes. Primero Harry oye voces extrañas y luego la hermana de Ron, Ginny, desaparece…",
	"b":"2"
	},//fin libro 2

	{"referencia":"book.html?b=3","imagen":"img/inicio/3.jpg", "titulo":"Harry Potter y el prisionero de Azkaban", 	
	"capitulos":"1.Lechuzas mensajeras<br>2.El error de tía Marge<br>3.El autobús Noctámbulo<br>4.El Caldero Chorreante<br>5.El dementor<br>6.Posos de té y garras de Hipogrifo<br>7.El boggart del armario ropero<br>8.La huída de la señora gorda<br>9.La derrota<br>10.El mapa del merodeador<br>11.La Saeta de Fuego<br>12.El Patronus<br>13.Gryffindor contra Ravenclaw<br>14.El rencor de Snape<br>15.La final de Quidditch<br>16.La predicción de la profesora Trelawney<br>17.El perro, el gato y la rata<br>18.Lunático, Colagusano, Canuto y Cornamenta<br>19.El vasallo de Lord Voldemort<br>20.El beso del dementor<br>21.El secreto de Hermione<br>22.Más lechuzas mensajeras<br>",
	"argumento":"Harry Potter y el prisionero de Azkaban fue publicada el 8 de julio de 1999 y fue aclamada en el mundo entero. El libro pasó cuatro semanas como número uno en las listas de libros de tapa dura para adultos más vendidos del Reino Unido.<br><br>Harry Potter, junto con sus mejores amigos, Ron y Hermione, está a punto de comenzar su tercer curso en el Colegio Hogwarts de Magia y Hechicería. Harry está deseando volver al colegio tras las vacaciones de verano (¿quién no lo desearía si vivieran con la horrible familia Dursley?). Pero cuando Harry llega a Hogwarts, el ambiente es tenso. Un asesino en serie se ha escapado y anda suelto, y los siniestros guardias de la cárcel de Azkaban han sido llamados para vigilar el colegio…",
	"b":"3"
	}, //fin libro 3

	{"referencia":"book.html?b=4","imagen":"img/inicio/4.jpg", "titulo":"Harry Potter y el cáliz de fuego", 
	"capitulos":"1.La Mansión de los Ryddle<br>2.La cicatriz<br>3.La invitación<br>4.Retorno a La Madriguera<br>5.Sortilegios Weasley<br>6.El traslador<br>7.Bagman y Crouch<br>8.Los Mundiales de quidditch<br>9.La Marca Tenebrosa<br>10.Alboroto en el Ministerio<br>11.En el Expreso de Hogwarts<br>12.El Torneo de los tres magos<br>13.Ojoloco Moody<br>14.Maldiciones imperdonables<br>15.Beauxbatons y Durmstrang<br>16.El Cáliz de fuego<br>17.Los cuatro campeones<br>18.La comprobación de las varitas mágicas<br>19.El colacuerno húngaro<br>20.La primera prueba<br>21.El Frente de Liberación de los Elfos Domésticos<br>22.Una prueba inesperada<br>23.El baile de Navidad<br>24.La primicia de Rita Skeeter<br>25.El huevo y el ojo<br>26.La segunda prueba<br>27.El regreso de Canuto<br>28.La locura del señor Crouch<br>29.El sueño<br>30.El pensadero<br>31.La tercera prueba<br>32.Hueso, carne y sangre<br>33.Los mortífagos<br>34.Priori incantatem<br>35.La poción de la verdad<br>36.Caminos separados<br>37.El comienzo<br>",
	"argumento":"Harry Potter y el cáliz de fuego, el cuarto libro de la serie, fue publicado el 8 de julio de 2000, con una primera tirada récord de un millón de ejemplares en el Reino Unido. Pronto rompió todos los récords en número de ejemplares vendidos en el primer día de publicación en el Reino Unido.<br><br>Las vacaciones de verano parecen no terminar nunca y Harry Potter está deseoso de comenzar el trimestre escolar. Es su cuarto curso en el Colegio Hogwarts de Magia y Hechicería y hay hechizos que aprender y (desafortunadamente) clases de Pociones y Adivinación a las que asistir. Pero Harry debe mantenerse en guardia en todo momento –su peor enemigo está preparando un horroroso destino para él."
	,"b":"4"
	}, //fin libro 4

	{"referencia":"book.html?b=5","imagen":"img/inicio/5.jpg", "titulo":"Harry Potter y la Orden del Fénix", 
	"capitulos":"1.Dudley demente<br>2.Picotazos de lechuzas<br>3.La escolta destacada<br>4.Numero 12, Grimmauld Place<br>5.La orden del Fénix<br>6.La antigua y noble casa de Black<br>7.El ministro de la magia<br>8.La audiencia<br>9.Los infortunios de la Señora Weasley<br>10.Luna Lovegood<br>11.La nueva canción del Sombrero Seleccionador<br>12.Profesora Umbridge<br>13.Detención con Dolores<br>14.Percy y Canuto<br>15.El Gran Inquisidor de Hogwarts<br>16.En “La Cabeza de Puerco”<br>17.Decreto educacional número 24<br>18.El Ejército de Dumbledore<br>19.El león y la serpiente<br>20.La historia de Hagrid<br>21.El ojo de la serpiente<br>22.Hospital San Mungo para enfermedades y lesiones mágicas<br>23.Navidad en el ala cerrada del hospital<br>24.Oclumancia<br>25.El escarabajo en la bahía<br>26.Visto e imprevisto<br>27.El centauro y el espía<br>28.El peor recuerdo de Snape<br>29.Orientación Vocacional<br>30.Grawp<br>31.T.I.M.O.s<br>32.Fuera del fuego<br>33.Lucha y huida<br>34.El departamento de misterios<br>35.Detrás del velo<br>36.El Único Que El Alguna Vez Temió.<br>37.La profecía perdida<br>38.El comienzo de la segunda guerra",
	"argumento":"El 21 de junio de 2003, se publicó Harry Potter y la Orden del Fénix en Gran Bretaña, Estados Unidos, Canadá y Australia. Esta quinta entrega de la series rompió todos los récords establecidos por Harry Potter y el cáliz de fuego, ya que se convirtió en el libro de venta más rápida de toda la historia.<br><br>Harry Potter debe empezar su quinto curso en el Colegio Hogwarts de Magia y Hechicería. Está desesperado por volver a Hogwarts y descubrir por qué sus amigos, Ron y Hermione, se han comportado de forma tan reservada durante todo el verano. Pero antes de llegar al colegio, Harry sobrevive a un terrorífico encuentro con dos Dementores, asiste a una visita en el Ministerio de Magia y es escoltado en un viaje nocturno en escoba al cuartel general secreto de un misterioso grupo denominado la Orden del Fénix…"
	,"b":"5"
	}, //fin libro 5

	{"referencia":"book.html?b=6","imagen":"img/inicio/6.jpg", "titulo":"Harry Potter y el misterio del príncipe", 
	"capitulos":"1.El otro Ministro<br>2.El Callejón de la Hilandera<br>3.Herencia y negaciones<br>4.Horace Slughorn<br>5.Un exceso de Flema<br>6.El desvío de Draco<br>7.El Club Slug<br>8.Snape victorioso<br>9.El Príncipe Mestizo<br>10.La Casa de Gaunt<br>11.Hermione echa una mano<br>12.Plata y óvalo<br>13.El acertijo secreto<br>14.Felix Felicis<br>15.El Juramento Inquebrantable<br>16.Una navidad muy fría<br>17.Una memoria lenta<br>18.Sorpresa de cumpleaños<br>19.Relatos élficos<br>20.La solicitud de Lord Voldemort<br>21.La habitación desconocida<br>22.Después del entierro<br>23.Horcruxes<br>24.Sectumsempra<br>25.La visión de la adivina<br>26.La cueva<br>27.La torre<br>28.La huída del Príncipe<br>29.El lamento del Fénix<br>30.La tumba blanca",
	"argumento":"Harry Potter y el misterio del príncipe se publicó en el Reino Unido, Estados Unidos y otros países de habla inglesa el 16 de julio de 2005. Este es el sexto libro de la serie y también fue un récord de ventas.<br><br>Es el sexto curso de Harry Potter en el Colegio Hogwarts de Magia y Hechicería. Las siniestras fuerzas de Voldemort se están reuniendo y una sensación de tristeza y miedo se apodera del lugar, así que a Harry le queda claro que pronto no tendrá más remedio que enfrentarse a su destino. ¿Estará Harry a la altura de las arriesgadas tareas que se le presentan?"
	,"b":"6"
	}, //fin libro 6

	{"referencia":"book.html?b=7","imagen":"img/inicio/7.jpg", "titulo":"Harry Potter y las reliquias de la muerte", 
	"capitulos":"1.El ascenso del Señor Tenebroso<br>2.En recuerdo<br>3.La despedida de los Dursley<br>4.Los siete Potters<br>5.Guerrero caído<br>6.El ghoul en pijama<br>7.El testamento de Albus Dumbledore<br>8.La boda<br>9.Un lugar donde esconderse<br>10.La historia de Kreacher<br>11.El trato<br>12.La magia es poder<br>13.La Comisión del Registro de los Nacidos de Muggles<br>14.El ladrón<br>15.La venganza del duende<br>16.El Valle de Godric<br>17.El secreto de Bathilda<br>18.La Vida y Mentiras de Albus Dumbledore<br>19.La cierva plateada<br>20.Xenophilius Lovegood<br>21.El Cuento de los Tres Hermanos<br>22.Las Reliquias de la Muerte<br>23.La Mansión de los Malfoy<br>24.El fabricante de varitas<br>25.Shell Cottage<br>26.Gringotts<br>27.El escondrijo final<br>28.El espejo extraviado<br>29.La diadema perdida<br>30.La destitución de Severus Snape<br>31.La Batalla de Hogwarts<br>32.La Varita de Saúco<br>33.La historia del Príncipe<br>34.El Bosque otra vez<br>35.King's Cross<br>36.El fallo en el plan<br>Epílogo: Diecinueve años después",
	"argumento":"Aunque Harry Potter y las reliquias de la muerte es una única novela, esta séptima entrega de las aventuras de Harry sirvió de base para dos películas. Como último libro de la serie, se publicó en el Reino Unido, en Estados Unidos y en otros países de habla inglesa el 21 de julio de 2007.<br><br>Harry Potter se está preparando para abandonar por última vez su hogar con los Dursley, en Privet Drive. El futuro que le espera está lleno de peligros, no solo para él, sino para todas las personas próximas a él –y Harry ya ha perdido demasiado. Solo destruyendo los restantes horcruxes de Voldemort podrá Harry liberarse y vencer a las fuerzas del mal del Señor de la Oscuridad. En un definitivo y peligroso viaje, Harry debe encontrar la fortaleza y la voluntad necesarias para entablar una batalla que solo él puede librar."
	,"b":"7"
	}, //fin libro 7 
];

