var juego = [
	{"titulo":"Harry Potter y la piedra filosofal", "referencia":"games.html?g=1",
	"captura":"img/juegos/c1.jpg", "portada":"img/juegos/g1.jpg", "g":"1",
	"plataformas":"• PC<br>• PSone<br>• Play Station 2 <br>• Xbox<br>• GameBoy Color <br>• Nintendo GameCube",
	"informacion":"Deja atrás el mundo muggle y apúntate al colegio Hogwarts de magia y hechicería en Harry Potter y la Piedra Filosofal.<br><br>Conviértete en Harry Potter, aprendiz de mago, y aprende a dominar todo lo mágico en un mundo lleno de hechicería, diversión y peligro. Supera increíbles desafíos y conoce a los inolvidables personajes del best-seller de J.K. Rowling en todo el mundo. <br><br>Los jugadores se convertirán en Harry Potter cuando se apunta a Hogwarts y se embarca en un viaje para revelar los secretos de sus propias dotes mágicas. Por el camino, Harry explorará las salas de Hogwarts y sus alrededores, estudiará para convertirse en mago, aprenderá Quidditch, recogerá objetos para resolver enigmas, realizará hechizos y pociones, descubrirá pasajes y lugares secretos y conocerá a los memorables personajes del mundo mágico de J.K. Rowling. <br><br>La versión incluye fases del juego basadas en el sigilo y tradicionales encuentros, en las que los jugadores guiarán a Harry por las salas de Hogwarts, avanzando a escondidas para evitar toparse con personajes entrometidos como Filch y Peeves. Muchas de las aventuras son dinámicas, en escenarios que cambian con el tiempo, como escaleras móviles y aulas que cambian de sitio. <br><br>Además, incluye un vertiginoso partido de Quidditch en estilo Arcade para sumergir aún más a los jugadores en el mundo mágico de Harry Potter."},

	{"titulo":"Harry Potter y la cámara secreta", "referencia":"games.html?g=2",
	"captura":"img/juegos/c2.jpg", "portada":"img/juegos/g2.jpg", "g":"2",
	"plataformas":"• PC<br>• PSone<br>• Play Station 2<br>• GameBoy Color<br>• GameBoy Advance<br>• Xbox",
	"informacion":"Desatendiendo el consejo de Dobby, el elfo doméstico, sobre el grave peligro que se avecina si regresa a Hogwarts, Harry se aventurará en su segundo año en Hogwarts y verá cómo se cumplen las predicciones de Dobby. Muy pronto Harry se verá envuelto en una oscura trama contra sus compañeros de clase cuando empiezan a quedarse petrificados. ¿Será culpa de Draco Malfoy o quizá se esconda algo más maligno detrás de todo esto? Con la vuelta de Hermione, Ron, Hagrid y de la lechuza Hedwig, por supuesto, el jugador podrá asistir a nuevas clases y aprender conjuros de Segundo año que le ayudará en su búsqueda para descubrir la verdadera identidad del heredero de la Casa Slytherin.<br><br>Podrás conversar con personajes como Myrtle la Llorona, comprar en el Callejón Diagon, explorar los complejos pasillos de Hogwarts y tomar importantes y decisivas decisiones en el mundo de Harry Potter.<br><br>Por supuesto, Harry podrá invocar conjuros contra enemigos, siempre que los ejecute a la perfección ya que, de lo contrario, podría tener graves, o incluso divertidas, consecuencias. Dentro de cada nivel, el jugador disfrutará de distintos mini juegos como ayudar a la Sra. Weasley a limpiar de gnomos su jardín, desafiar a otros estudiantes en el Club de Duelos del Profesor Lockhart o completar muchos otros mini juegos.<br><br>También puedes explorar las nuevas ambientaciones interactivas creadas y luchar por ganar la Copa para su Casa. Una vez que superes el curso en Pociones, Transformación y Herbología, empezarás a tomarle el gusto a ser el estudiante más famoso de Hogwarts mientras aprendes importantes conjuros y pociones necesarias para triunfar en La Cámara de los Secretos.<br><br>Se ha incorporado un impresionante y novedoso motor de juego para los usuarios de Game Boy Advance con el que reproducir los elementos renderizados aparecidos en los demás títulos de las otras plataformas. Además, el jugador podrá conectar su GBA a su Nintendo GameCube a través del Cable Link y transferir nuevos mapas, artículos mágicos y conjuros secretos.<br><br>El juego para Game Boy Color es un increíble RPG en 2D que guiará a Harry a través de un viaje sin fronteras hacia el mundo de Hogwarts. Incluye además partidos de Quidditch, duelos mágicos entre varios jugadores y los habitantes de Hogwarts, intercambio de cromos de Magos y Brujas Famosas y otros divertidos y mágicos mini juegos."},

	{"titulo":"Harry Potter y el prisionerio de Azkaban", "referencia":"games.html?g=3",
	"captura":"img/juegos/c3.jpg", "portada":"img/juegos/g3.jpg", "g":"3",
	"plataformas":"• PC<br>• Play Station 2<br>• Xbox<br>• Nintendo GameCube<br>• GameBoy Advance",
	"informacion":"Juega como Harry, Ron o Hermione y enfréntate a los rivales más terroríficos hasta ahora: el convicto escapado Sirius Black y los temibles Dementores de Azkaban en el tercer año en Hogwarts.<br><br>Por primera vez, podrás jugar con Harry Potter y sus amigos Ron Weasley y Hermione Granger, utilizando sus atributos y habilidades clave para superar los desafíos y vencer a los enemigos. Los tres alumnos de la escuela de magos y brujas más famosa tendrán que aunar fuerzas y dominar nuevos hechizos para enfrentarse a los rivales más aterradores hasta el momento: el reo escapado de Azkaban, Sirius Black, y los Dementores, siniestros guardias de la cárcel.<br><br>Desde la escena introductoria en el Hogwarts Express, hasta el final a orillas del gran lago de Hogwarts, el videojuego Harry Potter y el prisionero de Azkaban introduce a los jugadores en el mundo mágico de Harry Potter. Se desentraña el misterio entorno a Sirius Black y su huida de Azkaban, la espantosa prisión para magos, adentrándose en la aventura más emocionante y compleja de Harry Potter hasta el momento. Lucharás contra un montón de nuevos personajes y criaturas, te atreverás con una serie de búsquedas secundarias, volarás a lomos de un Hipogrifo, descubrirás los secretos del Mapa del Merodeador y te enfrentarás en múltiples desafíos de dos jugadores.<br><br>"},

	{"titulo":"Harry Potter y el cáliz de fuego", "referencia":"games.html?g=4",
	"captura":"img/juegos/c4.jpg", "portada":"img/juegos/g4.gif", "g":"4",
	"plataformas":"• Play Station 2<br>• PSP<br>• Xbox<br>• Nintendo GameCube<br>• Nintendo DS<br>• GameBoy Advance<br>• PC",
	"informacion":"Esta nueva aventura hará a los jugadores revivir momentos excitantes de la película y aplicarán su magia hasta la prueba final, en modo cooperativo, para jugar con hasta dos amigos. <br><br>En Harry Potter y El Cáliz del Fuego, Harry es misteriosamente seleccionado como el cuarto participante en el peligroso Torneo de los Tres Magos. Cada participante de este torneo internacional debe enfrentarse a un dragón escupefuegos, rescatar a sus amigos de las profundidades del Lago Negro, y adentrarse en los retorcidos misterios de una inmensa y peligrosa maraña. Los jugadores vivirán todas las emociones de la película – ¡desde la Copa del Mundo de Quidditch hasta el apasionante duelo con el mismo Lord Voldemort! <br><br>Harry, Ron, y Hermione son todos personajes jugables y están modelados con sus homónimos de la gran pantalla."},

	{"titulo":"Harry Potter y la Orden del Fénix", "referencia":"games.html?g=5",
	"captura":"img/juegos/c5.jpg", "portada":"img/juegos/g5.jpg", "g":"5",
	"plataformas":"• GameBoy<br>• Play Station 2<br>• Play Station 3<br>• Nintendo DS<br>• Xbox 360<br>• PSP<br>• Nintendo Wii<br>• PC<br>• Telefonía móvil",
	"informacion":" Harry regresa a Hogwarts en su quinto año de estudios y descubre que la gran parte de la comunidad de magos desconoce la verdad sobre su encuentro con Lord Voldemort. Por temor a que el Director de Hogwarts, Albus Dumbledore, esté mintiendo sobre el regreso de Voldemort para reducir su poder y quitarle el puesto, el Ministro de Magia, Cornelius Fudge, designa a una nueva profesora de Defensa Contra las Artes Oscuras para mantener controlados a Dumbledore y a los estudiantes de Hogwarts. Pero ésta decide que las clases sean completamente teóricas haciendo caso omiso a los avisos de peligro, y así dejando indefensos a los alumnos, por lo que Harry, con la ayuda de sus amigos Hermione y Ron, reunirá en secreto a un pequeño grupo de estudiantes que se autodenominan 'El Ejército de Dumbledore', y les enseñará a defenderse de las Artes Oscuras, preparando a los jóvenes y valientes magos para la extraordinaria batalla que está por venir."},

	{"titulo":"Harry Potter y el misterio del príncipe", "referencia":"games.html?g=6",
	"captura":"img/juegos/c6.jpg", "portada":"img/juegos/g6.jpg", "g":"6",
	"plataformas":"• Wii<br>• PS2<br>• PS3<br>• Xbox 360<br>• PSP<br>• Nintendo DS<br>• PC<br>• Telefonía móvil",
	"informacion":"Volveremos al sexto curso de Harry en Hogwarts, tendremos duelos (con la misma estética que en La Cámara de los Secretos), clases de Pociones y cómo no, podremos formar parte del equipo de Quidditch de Gryffindor.<br><br>La fecha oficial del lanzamiento del videojuego será el día 14 de julio de 2009.<br><br>Como curiosidad, vale destacar que Electronic Arts realizó un concurso entre fans en el cual los ganadores aparecerán en los retratos de Hogwarts, además de un excelente viaje a los estudios Bright Light de EA en Guildford, Inglaterra.<br><br>El videojuego ya ha sido doblado y contará con las voces originales de Hermione, Draco o el Señor Tenebroso, las que no escucharemos en el cine. Quien quiera oír a Hermione con la voz de las cuatro primeras películas tendrá que ir a la versión jugable.<br><br>Del videojuego también hemos averiguado que Emma Watson es la única que pone su voz del trío, dejando Harry y Ron a actores profesionales del doblaje. En España es doblada por Michelle Jenner, actualmente rostro conocido por su papel de Sara en Los Hombres de Paco (Antena 3), que a pesar de su éxito no ha querido pasar la oportunidad de trabajar de nuevo a las órdenes de Gutiérrez en el videojuego.<br><br>Otros personajes que aparecerán en el videojuego, a juzgar por la ficha de doblaje, son los profesores, compañeros de Harry y Bellatrix, Fenrir y varios retratos de Hogwarts. También un nuevo personaje: Timothy el Tímido."},

	{"titulo":"Harry Potter y las reliquias de la muerte I", "referencia":"games.html?g=7",
	"captura":"img/juegos/c7.jpg", "portada":"img/juegos/g7.jpg", "g":"7",
	"plataformas":"• Microsoft Windows<br>• Nintendo DS<br>• Nintendo Wii<br>• Playstation 3<br>• Xbox 360<br>• Plataformas móviles",
	"informacion":"Harry Potter, Ronald Weasley y Hermione Granger deben aventurarse en el mundo mágico y el mundo muggle por su cuenta para destruir los restantes Horrocruxes de Lord Voldemort. En su viaje, se encontrarán con numerosos peligros como mortífagos, carroñeros y mucho más. Ningún lugar es seguro... no se puede confiar en nadie.... la batalla ha comenzado."},

	{"titulo":"Harry Potter y las reliquias de la muerte II", "referencia":"games.html?g=8",
	"captura":"img/juegos/c8.jpg", "portada":"img/juegos/g8.jpg", "g":"8",
	"plataformas":"• PC <br>• Nintendo DS<br> • PlayStation 3<br> • Xbox 360<br> • Wii",
	"informacion":"A medida que el mundo mágico se hunde en el caos, Harry, Ron y Hermione tiene la terrible misión de destruir los Horrocruxes finales de Lord Voldemort y ésta tarea final llega como algo más grande y más peligroso de lo que pudieran imaginar. La misión terminará en Hogwarts, donde la gran batalla entre el bien y el mal se lleva a cabo. Harry y Voldemort luchan por la última vez."}
]