var personaje = [
	{"nombre":"Harry Potter", "actuacion":"Daniel Radcliffe","imagen":"img/personajes/harry.gif", "referencia":"personage.html?p=1", "p":"1", 
	"informacion":"Harry James Potter, nacido el 31 de Julio de 1980, es el personaje principal de la serie de libros creada por la autora JK Rowling.<br><br>Su historia se desarrolla en la Escuela Hogwarts de Magia y Hechicería, junto a sus mejores amigos, Ron Weasley y Hermione Granger. Su característica física más intrigante, es una cicatriz con forma de relámpago en su frente, la cual obtuvo cuando el Mago Oscuro Lord Voldemort intentó asesinarlo cuando sólo era un bebé de 1 año de edad, mediante la maldición asesina, Avada Kedavra. Voldemort asesinó a los padres de Harry y destruyó su hogar la noche del 31 de Octubre de 1981. Harry es famoso dentro del mundo mágico, por ser la única persona que ha sobrevivido al Avada Kedavra, causando la caída de Lord Voldemort."},

	{"nombre":"Ron Weasley", "actuacion":"Rupert Grint","imagen":"img/personajes/ron.gif", "referencia":"personage.html?p=2", "p":"2", 
	"informacion":"Ronald 'Ron' Billius Weasley, nacido el 1 de marzo de 1980, es el hijo de Arthur Weasley y Molly Weasley, siendo el sexto de siete hijos, y el varón más joven. Ron creció en el hogar de su familia, La Madriguera, cerca de la villa de Ottery St. Catchpole en Devon. Ron tiene cinco hermanos, Bill, Charlie, Percy, los gemelos Fred y George, y una hermana menor, Ginny.<br><br>A los once años fue aceptado en el Colegio Hogwarts de Magia y Hechicería y empezó sus estudios mágicos el 1 de Septiembre de 1991 y fue seleccionado para la casa Gryffindor. Desde el primer año se convirtió en el mejor amigo de Hermione Granger y Harry Potter."},

	{"nombre":"Hermione Granger", "actuacion":"Emma Watson","imagen":"img/personajes/hermione.gif", "referencia":"personage.html?p=3", "p":"3", 
	"informacion":"Hermione Jean Weasley, (de soltera Granger) nacida el 19 de septiembre de 1979, es la hija de los muggles Sr. y Sra. Granger, ambos dentistas en el mundo muggle. A los once años descubrió su don mágico y fue aceptada en el Colegio Hogwarts de Magia y Hechicería. Hermione empezó sus estudios mágicos el 1 de septiembre de 1991, poco antes de cumplir doce años y fue seleccionada para la Casa de Gryffindor. Posee una mente académica brillante, y demostró ser una estudiante superdotada.<br><br>Hermione conoció a Harry Potter y a Ron Weasley en el Expreso de Hogwarts. Los dos chicos encontraron a Hermione una chica hostil y sabelotodo. Después de ver el afán con los profesores y sus constantes respuestas correctas refuerzan su primera impresión. Sin embargo, a pesar de la fría relación entre los tres, Hermione dio un paso asumiendo la responsabilidad después de que la había salvado de un troll en Halloween. Harry y Ron se sorprendieron pero lo agradecieron, y los tres rápidamente se convirtieron en amigos."},

	{"nombre":"Albus Dumbledore", "actuacion":"Richard Harris/Michael Gambón","imagen":"img/personajes/albus.png", "referencia":"personage.html?p=4", "p":"4", 
	"informacion":"El profesor Albus Percival Wulfric Brian Dumbledore, Orden de Merlín - Primera Clase , Gran Hechicero, Jefe de Magos del Wizengamot, Jefe Supremo, (4 de marzo, 1881 - 30 de junio, 1997). Fue profesor de Transformaciones,  y más tarde director del Colegio Hogwarts de Magia y Hechicería.<br><br>Era un mago mestizo, hijo de Percival Dumbledore y Kendra Dumbledore, y hermano mayor de Aberforth y Ariana.<br><br>Era considerado como el mago más poderoso de su tiempo. Él era famoso por derrotar a Gellert Grindelwald, descubrir doce usos de la sangre de dragón, y su trabajo en alquimia con Nicolas Flamel."},

	{"nombre":"Minerva McGonagall", "actuacion":"Maggie Smith","imagen":"img/personajes/McGonagall.png", "referencia":"personage.html?p=5", "p":"5", 
	"informacion":"Madam Profesora Minerva McGonagall (n. 4 de octubre de 1935) es una bruja que asistió al Colegio Hogwarts de Magia y Hechicería en 1947 y fue ubicada por el Sombrero Seleccionador en la Casa Gryffindor. Teniendo en cuenta que también podía pertenecer a la Casa Ravenclaw gracias a su enorme inteligencia. Tras su educación volvió a Hogwarts y se convirtió en la Jefa de la Casa de Gryffindor, profesora de Transformaciones y al mismo tiempo Directora adjunta del colegio Hogwarts. También era una Animaga, tomando la forma de un gato."},

	{"nombre":"James Potter I", "actuacion":"Adrian Rawlins","imagen":"img/personajes/James.jpg", "referencia":"personage.html?p=6", "p":"6", 
	"informacion":"James Potter (27 de Marzo de 1960 -- 31 de Octubre de 1981) también conocido como Cornamenta, fue un mago de sangre pura e hijo de Charlus Potter y Dorea Potter (antiguamente Black). Ingreso al Colegio Hogwarts de Magia y Hechicería en 1971 y se gradúo en 1978, perteneciendo a la casa de Gryffindor. Al empezar el Colegio, conoció a sus mejores amigos Sirius Black, Remus Lupin y Peter Pettigrew. También conoció a Severus Snape, quién fue inmediatamente su rival, y a Lily Evans, su interés romántico.<br><br>Durante su septimo año, James fue nombrado Premio Anual y empezo a salir con Lily Evans, quién luego fue su esposa. Juntos, tuvieron un hijo llamado Harry. James, Lily y sus amigos lucharon en la Primera Guerra Magica como miembros de la Orden del Fénix, él y su esposa se enfrentaron a Lord Voldemort tres veces. Además, James y Lily tuvieron que esconderse despues de escuchar la Profecia relacionada con Lord Voldemort y su pequeño hijo. Trágicamente, James y Lily fueron traicionados por uno de sus amigos, Peter Pettigrew. James fue asesinado por Voldemort en el Valle de Godric en 1981 tratando de proteger a su hijo. Luego James aparece nuevamente por la Piedra de la Resurrección junto a Lily, Sirius y Remus"},

	{"nombre":"Lily Potter", "actuacion":"Geraldine Somerville","imagen":"img/personajes/lily.jpg", "referencia":"personage.html?p=7", "p":"7", 
	"informacion":"Lily Potter (de soltera Evans) (30 de enero de 1960 - 31 de octubre de 1981) fue una bruja hija de muggles, la hija menor del Sr. y la Sra. Evans, hermana de Petunia. Ella descubrió que era una bruja cuando era una niña, después de que un niño que vivía cerca de ella (Severus Snape) le contó de la existencia de la magia. Los dos se hicieron grandes amigos, comentando y aprendiendo de Severus sobre el mundo de la magia Lily creció un poco distante a su hermana Petunia. Ella comenzó a asistir al colegio Hogwarts desde 1971 hasta el 1978, y estuvo dentro de la casa de Gryffindor. Talentosa estudiante, Lily fue miembro del club del profesor Horace Slughorn. Su amistad con Snape terminó en quinto año, después de que él, en un momento de frustración y vergüenza, la llamara sangre sucia. Aunque Snape siempre la amó, Lily se casó con James Potter. Ella y James se unieron a la Orden del Fénix después de graduarse y pelearon en la Primera Guerra Mágica, enfrentándose ella misma a Lord Voldemort en tres ocasiones. Esto hizo que éste persiguiera a su único hijo (Harry Potter) cuando una profecía declaró que una persona tendría poder para destruirlo; así que Voldemort atacó a los Potter el 31 de octubre de 1981. Después de matar a James, le ofreció a Lily la oportunidad de huir, a pedido de Snape, pero Lily se negó y Volvemort la mató. Este sacrificio de amor le dio a su hijo, Harry, tal protección que lo convirtió en la única persona capaz de sobrevivir a la maldición asesina."},
	
	{"nombre":"Severus Snape", "actuacion":"Alan Rickman","imagen":"img/personajes/snape.png", "referencia":"personage.html?p=8", "p":"8", 
	"informacion":"El Profesor Severus Snape (9 de enero de 1960 - 2 de mayo de 1998) fue profesor de Pociones (1982-1996), profesor de Defensa Contra las Artes Oscuras (1996-1997) y director (1997-1998) de Hogwarts, a la que asistió como estudiante desde 1971 hasta 1978. Snape juega un papel muy importante en las dos guerras contra Lord Voldemort.<br><br>Severus Snape era un mago de sangre mestiza, hijo de la bruja Eileen Prince, y del muggle Tobias Snape. Fue criado en una vivienda muggle de la calle de la Hilandera que estaba muy cerca de la casa de la familia Evans. Conoció a Lily y Petunia Evans cuando tenía nueve años, y se enamoró profundamente de Lily, convirtiéndose en el mejor amigo de ella. En 1971 comenzó su primer año en Hogwarts, donde fue seleccionado para Slytherin. Severus se convirtió en el enemigo inmediato de James Potter y Sirius Black y fue una víctima frecuente de sus bromas.<br><br>Snape fue desarrollando una pasión a la Artes Oscuras a una edad temprana, y prefirió la supremacía de la sangre pura en la Casa Slytherin, a pesar de su amor por Lily Evans , que era hija de muggles. Esto puso en riesgo su amistad con Lily. Después de salir de la escuela se unió a los mortífagos, junto con varios de sus compañeros de Slytherin.<br><br>Poco antes de que Lily Evans fuera asesinada por Lord Voldemort, Snape se cambió de bando y se convirtió en miembro de la Orden del Fénix al año siguiente y sirvió de agente doble durante la Segunda Guerra Mágica (1995-1998). Con enorme dificultad, Snape fue capaz de evitar que Lord Voldemort revelara la verdad acerca de su lealtad. A pesar de las opiniones de la mayoría de los demás, Albus Dumbledore siempre confió en Snape por razones que se mantuvieron entre los dos hasta sus muertes. Después de su muerte, se revela que su profundo amor por Lily Evans lo llevó a arrepentirse, uniéndose a la causa de Dumbledore. La relación entre Dumbledore y Snape sería una en la que se forma una fuerte lealtad, hasta el punto de que Snape mata a Dumbledore porque éste último se lo pide. Antes de la muerte de Dumbledore, Snape se comprometió a proteger a los estudiantes de Hogwarts de los mortífagos, que inevitablemente iban a tomar el control del Ministerio de la Magia, así como del colegio. Snape más tarde participó en la Batalla de Hogwarts, pero fue asesinado por Nagini, la serpiente Horrocrux de Lord Voldemort quien se lo ordenó porque equivocadamente creía que Snape era el amo de la Varita de Saúco, una varita poderosa que Voldemort quería. Después de su muerte, Harry Potter se aseguró de que el retrato de Severus Snape se colocara en el despacho del director de Hogwarts, en honor a su heroísmo, a pesar de sus importantes diferencias personales."},
	
	{"nombre":"Sirius Black", "actuacion":"Gary Oldman","imagen":"img/personajes/sirius.png", "referencia":"personage.html?p=9", "p":"9", 
	"informacion":"Sirius Black III (1959- 18 de junio de 1996), también conocido como Canuto u Hocicos, fue un mago de Sangre limpia, hijo de Orion y Walburga Black y hermano mayor de Regulus. Aunque era el heredero de la Familia Black, Sirius estaba en desacuerdo con las creencias de su familia en la pureza de la sangre desafiando a su familia al ser colocado en Gryffindor en lugar de Slytherin en el Colegio Hogwarts de Magia y Hechicería, al que asistió entre 1971 y 1978. Mientras la relación de Sirius con sus familiares se deterioraba, el creó una gran amistad con Remus Lupin,  Peter Pettigrew y especialmente con James Potter. Los cuatro amigos, también conocidos como Los Merodeadores, se unieron a la Orden del Fénix para luchar contra Lord Voldemort y sus mortífagos durante la Primera Guerra Mágica. Sirius también se volvió padrino de Harry Potter, hijo de James Potter y Lily Evans. Sin embargo, Peter Pettigrew traicionó a los Potter con Voldemort y Sirius fue culpado de la muerte de James y Lily Potter, al igual que de la muerte de Peter Pettigrew y doce Muggles durante su escape.<br><br>Sirius fue enviado a Azkaban por doce años, eventualmente se convirtió en el primer caso conocido de fuga de la prisión tomando la forma de un gran perro negro debido a sus habilidades como Animago. Sirius demostró la culpabilidad de Pettigrew a su viejo amigo Remus y a su ahijado, Harry Potter. Después de que Lord Voldemort regresara en 1995, Sirius se volvió a unir a la Orden del Fénix. Fue asesinado por su prima Bellatrix Lestrange durante la Batalla del Departamento de Misterios. Gracias a la Piedra de la Resurrección, Sirius aparece ante Harry en compañía de James, Lily y Remus en 1998."},

	{"nombre":"Remus Lupin", "actuacion":"David Thewlis","imagen":"img/personajes/remus.png", "referencia":"personage.html?p=10", "p":"10", 
	"informacion":"También conocido como Lunatico. Este hombre-lobo perteneció a la Orden del Fénix y, durante un curso, fue profesor de Hogwarts. Era amigo de Sirius Black y también de James Potter. Poseedor de un carácter conciliador y ambiguo, solía huir siempre del enfrentamiento directo, recurriendo a la diplomacia y la astucia. De vestimenta generalmente pobre, con aspecto pálido y enfermizo, usaba una talla mediana, con el cabello castaño entrecano.<br><br>Remus hizo una muy buena amistad con sus compañeros James Potter, Sirius Black y Peter Pettigrew. Mantuvo su condición de hombre lobo escondida de los demás, poniendo escusas para cada escapada, por miedo al rechazo. Sin embargo, en su segundo año fue descubierto por sus tres amigos. Para su sorpresa, éstos no sólo lo aceptaron, sino que más adelante se convirtieron en animagos para hacer más amenas sus transformaciones. Cada noche se reunían en la casa de los gritos, y después deambulaban por los terrenos de Hogwarts. Se llamaron a sí mismos los merodeadores y juntos crearon el Mapa del Merodeador."},
	
	{"nombre":"Ginny Weasley", "actuacion":"Bonnie Wright ","imagen":"img/personajes/ginny.png", "referencia":"personage.html?p=11", "p":"11", 
	"informacion":"Ginevra 'Ginny' Molly Potter (de soltera Weasley) nació el 11 de agosto de 1981. Es la menor de los hijos de Arthur Weasley y Molly Weasley y la primera hija mujer en la familia Weasley en muchos siglos. Según sus hermanos, Fred y George Weasley su pequeño tamaño no se relaciona con sus claras habilidades como bruja. Asistió a Hogwarts desde 1992 a 1998. En su primer año, fue poseída por un Horrocrux de Lord Voldemort , y fue forzada a reabrir la Cámara de los Secretos, poniendo en riesgo la vida de muchos estudiantes, y la suya propia. Desde eso, Ginny creció como una mujer con confianza en sí misma, convirtiéndose en miembro del Ejército de Dumbledore, peleando en la batalla del Departamento de Misterios, la batalla en la Torre de Astronomía, y la Batalla de Hogwarts. También es una excelente jugadora de Quidditch en Hogwarts, y después jugando profesionalmente para las Arpías de Holyhead. Se casó con Harry Potter en algún punto entre los años 1998 y 2017, y tuvieron tres hijos: James Sirius, Albus Severus y Lily Luna."},
	
	{"nombre":"Fred y George Weasley", "actuacion":"James y Oliver Phelps","imagen":"img/personajes/gemelos.jpg", "referencia":"personage.html?p=12", "p":"12", 
	"informacion":"Fred y George Weasley fueron dos magos gemelos nacidos el 1 de abril de 1978. Fueron los hermanos menores de Bill, Charlie y Percy, son los hermanos mayores de Ron y Ginny. Ambos son bromistas expertos, empezaron sus estudios en Hogwarts en 1989 y fundaron la tienda de artículos de broma Sortilegios Weasley y fueron miembros del Ejército de Dumbledore y de la Orden del Fénix.<br><br>Para el septimo libro sus roles cambian completamente, George pierde una oreja en la 'batalla de los siete Harrys' bajo el hechizo Sectumsempra lanzado por Severus Snape y junto con Fred, él y George empiezan a bromear y llamarse desorejado. Fred lamentablemente muere cuando August Rookwood le lanza accidentalmente una maldición que destruye gran parte del castillo en la Batalla de Hogwarts, un final muy triste para los personajes mas carismáticos de la saga.<br><br>En el epilogo, se muestra a George casado con Angelina Jhonson. Tiene 2 hijos, Fred II y Roxane Weasley, George nunca se recuperara de la muerte de su hermano, por lo que le puso como nombre a su hijo Fred II."},
	
	{"nombre":"Neville Longbottom", "actuacion":"Matthew David Lewis","imagen":"img/personajes/neville.png", "referencia":"personage.html?p=13", "p":"13", 
	"informacion":"El Profesor Neville Longbottom (n. 30 de julio de 1980) es el actual profesor de Herbología de Hogwarts, que asistió al Colegio Hogwarts de Magia y Hechicería en 1991, y fue ubicado en la Casa Gryffindor. Sus padres, Alice y Frank Longbottom, eran unos muy respetados Aurores y miembros de la primera Orden del Fénix. Poco después del nacimiento de Neville, fueron torturados hasta la locura por cuatro mortífagos (Bellatrix Lestrange , Rodolphus Lestrange, Rabastan Lestrange y Barty Crouch Jr. ) con la maldición Cruciatus y debido a esto terminaron internados en la Sala de Janus Thickey en el Hospital San Mungo de Enfermedades y Heridas Mágicas, dejando a Neville ser criado por su abuela.<br><br>A lo largo de sus años en el colegio, Neville pasó de ser un chico tímido e introvertido a ser un valiente defensor de Hogwarts. Él era un miembro importante del Ejército de Dumbledore, luchó en la Batalla del Departamento de Misterios, la Batalla de la Torre de Astronomía y la Batalla de Hogwarts. Durante la Batalla de Hogwarts, después de haber rechazado la invitación para unirse a Voldemort por parte de los mortífagos, destruyó el séptimo y último Horrocrux cuando decapitó a Nagini."},
	
	{"nombre":"Nymphadora Tonks", "actuacion":"Natalia Tena","imagen":"img/personajes/tonks.png", "referencia":"personage.html?p=14", "p":"14", 
	"informacion":"Nymphadora Tonks (c. 1973 - 2 de mayo de 1998) era hija de Andromeda Black y Ted Tonks. Prefiere ser llamada 'Tonks', asistió al Colegio Hogwarts de Magia y Hechicería entre 1984 y 1991, y perteneció a la Casa Hufflepuff. Después de salir de Hogwarts, se incorporó el Ministerio de Magia y se entrenó para convertirse en un Auror en virtud de Alastor Moody, calificando en 1994. En 1995, se incorporó a la reconstituida Orden del Fénix, trabajaba encubierta en el Ministerio y ayudaba a la guardia del Departamento de Misterios. En junio de 1996, ella luchó en la Batalla del Departamento de Misterios, y en algún momento se enamoró de Remus Lupin. Remus, quien decía que era demasiado mayor, pobre y peligroso para ella, rechazó sus sentimientos, aunque a su juicio él sentía lo mismo. A raíz del regreso de Lord Voldemort reconocido por el Ministerio de Magia en 1997, a Tonks se le asignó vigilar Hogsmeade, como parte de ser Auror, más tarde luchó en la Batalla de la Torre de Astronomía, y, después de ver el amor que Fleur Delacour sentía por Bill Weasley, a pesar de sus heridas,declaró públicamente su amor por Remus. Los dos se casaron en el verano de 1997, y Tonks quedó embarazada poco después. Ella dio a luz a su hijo,Ted Lupin, poco después de Semana Santa en 1998. En mayo de ese mismo año, Tonks luchó en la Batalla de Hogwarts, y fue asesinada por su tía, Bellatrix Lestrange. Nymphadora Tonks es la prima de Draco Malfoy."},
	
	{"nombre":"Cedric Digory", "actuacion":"Robert Pattinson","imagen":"img/personajes/cedric.png", "referencia":"personage.html?p=15", "p":"15", 
	"informacion":"Cedric Diggory (31 de Octubre 1977 - 24 de junio de 1995) era el capitán y buscador del equipo de Quidditch de Hufflepuff durante el tercer y cuarto año de Harry. El padre de Cedric, Amos Diggory, trabaja en el Ministerio de Magia. Su novia era Cho Chang, y durante el curso fue prefecto de Hogwarts. Cedric Diggory fue elegido como campeón de Hogwarts para el Torneo de los tres magos.<br><br>Durante la tercera y última prueba del torneo, en el laberinto, Cedric se niega a tomar la copa sin Harry, ya que se habían ayudado mutuamente durante toda la prueba, por lo que la agarran juntos.<br><br>La copa termina siendo un traslador que los lleva con Lord Voldemort y su vasallo Colagusano (Petter Pettigrew). Colagusano mata a Diggory bajo órdenes de Voldemort, usando la maldición Avada Kedavra. Harry logra escapar, llevando el cuerpo de Cedric a su padre."},
	
	{"nombre":"Luna Lovegood", "actuacion":"Evanna Lynch","imagen":"img/personajes/luna.png", "referencia":"personage.html?p=16", "p":"16", 
	"informacion":"Luna Scamander, es una bruja que asistió al Colegio Hogwarts de Magia y Hechicería desde 1992 hasta 1999 y pertenece a la Casa Ravenclaw. Es muy común verla con el trío, con Neville Longbottom y Ginny Weasley, siendo la única alumna de otra casa que se relaciona directamente con Gryffindor.<br><br>Su padre es Xenophilius Lovegood, director de la revista El Quisquilloso, que Luna siempre lee (en ocasiones al revés, asegurando que aparecen hechizos ocultos en ella). El diario es absurdo y cuenta muchas fanfarronadas, como es el caso del 'nombre en clave' de Sirius Black, y la revuelta de duendes de Cornelius Fudge.<br><br>Su madre era una bruja muy capaz a la que le gustaba experimentar. Cuando Luna tenía nueve años, un experimento de su madre salió mal y falleció. Luna todavía la echa de menos a veces, pero piensa que la verá otra vez un día en la vida después de la muerte."},
	
	{"nombre":"Cho Chang", "actuacion":"Katie Leung ","imagen":"img/personajes/cho.png", "referencia":"personage.html?p=17", "p":"17", 
	"informacion":"Cho Chang (nacida c. 1979) fue una bruja que asistió a Colegio Hogwarts de Magia y Hechicería desde 1990 a 1997 y fue elegida para la Casa de Ravenclaw. Fue buscadora del Equipo de Quidditch de Ravenclaw y una estudiante popular.<br><br>Cho fue novia de Cedric Diggory en el cuarto libro y tras la muerte de este quedo 'traumatizada', llorando siempre por él por todos los rincones del colegio.<br><br>Cho sale con Harry en el quinto libro pero no llegan a durar mucho y, a final de este, descubrimos que Harry deja de tener interés en ella porque, según dice Ron, es una chica poco alegre.<br><br>"},
	
	{"nombre":"Horace Slughorn", "actuacion":"Jim Broadbent","imagen":"img/personajes/slughorn.jpg", "referencia":"personage.html?p=18", "p":"18", 
	"informacion":"Horace E. F. Slughorn fue profesor de pociones y jefe de la casa Slytherin en el Colegio Hogwarts de Magia y Hechizeria. Fue profesor de pociones durante más de cincuenta años y jefe de Slytherin antes de jubilarse en 1981. Fue amigo y colega de Albus Dumbledore, quien lo persuadió a regresar para ocupar el cargo en 1996.<br><br>El Club de las Eminencias o Club Slug fue 'fundado' por el profesor Slughorn con el fin de reunir en él sólo a estudiantes que tengan o hayan tenido conocidos o familiares con algún puesto importante en ciertos ámbitos del mundo de la magia, tal es el caso de puestos importantes en el Ministerio de Magia, haber tenido alguna Orden de Merlín, que sean jugadores reconocidos dentro del mundo del Quidditch o que simplemente hayan sido famosos; también admite a estudiantes que sean prometedores no necesariamente con parientes importantes (tal es el caso de Lily Potter, Hermione Granger o Ginny Weasley).<br><br>A este club asisten alumnos como Harry Potter, Hermione Granger, Ginny Weasley, Neville Longbottom, Blaise Zabini, Cormac McLaggen entre otros. No existían días específicos para juntarse, simplemente el profesor citaba a sus alumnos por medio de notas que enviaba a través de otros alumnos o hacia correr la voz. El sitio usual de reunión era el despacho del profesor Slughorn."},
	
	{"nombre":"Dobby", "actuacion":" - ","imagen":"img/personajes/dobby.jpg", "referencia":"personage.html?p=19", "p":"19", 
	"informacion":"Dobby (Nacido el 27 de Junio de 1965. Muere el 28 de Marzo de 1998) fue el elfo Doméstico de la familia Malfoy hasta su liberación el 24 de junio de 1993.<br><br>Dobby es considerado por los demás elfos como extraño, pues le gusta la libertad y exige pago por su trabajo aunque siempre le obedeció a Harry, Ron y Hermione y se lastimaba si no lo hacía.<br><br>En 1998, Harry, Ron, Hermione, Dean, Luna, Griphook son secuestrados por los Mortífagos en la mansión de los Malfoy, Dobby aparece allí y los libera. Luego usa su magia para luchar contra los mortífagos, y durante la lucha, Bellatrix Lestrange lanza un puñal justo cuando Dobby los teletransporta a 'El refugio'. La daga le da, y cuando llegan, Dobby, que está lejos de Harry, lo llama, Harry va a socorrerlo pero la herida es muy grave, Dobby dice sus últimas palabras y muere al poco tiempo."},
	
	{"nombre":"Garrick Ollivander", "actuacion":"John Hurt","imagen":"img/personajes/Ollivander.jpg", "referencia":"personage.html?p=20", "p":"20", 
	"informacion":"Olivander es un fabricante y vendedor de varitas mágicas y es el dueño de la tienda de varitas mágicas llamada Ollivander's, que se encuentra en el Callejón Diagon. Se sabe, gracias a Pottermore que quedó en la casa Ravenclaw.<br><br>Aparece por primera vez en Harry Potter y la piedra filosofal Cuando le vendió la varita mágica a Harry Potter.<br><br>Reaparece en el cuarto libro como encargado de la comprobación de las varitas mágicas de los participantes del Torneo de los Tres Magos.<br><br>Fue secuestrado en el sexto libro por los Mortífagos por orden de Voldemort aprovechando que tenía muy buenos conocimientos sobre varitas mágicas para preguntarle cómo evitar otro Priori Incantatem con Harry Potter y además usar sus contactos con otros fabricantes para poder localizar y encontrar la Varita de Saúco. Es rescatado por Dobby de la mansión de los Malfoy en el séptimo libro, alojándose en la casa de Bill y Fleur donde le explica a Harry que su varita mágica no se puede reparar. Poco después se va a vivir con los Weasley protegiéndose de otro secuestro para así ser ésta su última aparición en la serie."},
	
	{"nombre":"Tom Marvolo Riddle", "actuacion":"Ralph Fiennes","imagen":"img/personajes/voldemort.jpg", "referencia":"personage.html?p=21", "p":"21", 
	"informacion":"Posteriormente conocido como Lord Voldemort, fue el mago tenebroso más poderoso de todos los tiempos. Siendo hijo del adinerado muggle Tom Riddle Sr. y la bruja Mérope Gaunt, nació con sangre mestiza, su madre murió poco después de dar a luz. Tom Riddle Sr. dejó a su esposa una vez que ella quedó encinta, habiéndose librado del conjuro de una poción de amor, la cual había sido la única causa de su relación. Su hijo, Tom Riddle, nació y fue criado en un orfanato muggle, aunque no tardó en ingresar al Colegio Hogwarts de Magia y Hechicería e incorporarse a la casa Slytherin. Tom Riddle fue durante su vida temprana considerado el alumno más talentoso que jamás hubiera asistido a Hogwarts .<br><br>Aunque al principio permaneció oculto, Voldemort no tardó en revelarse, comenzando una sangrienta reconquista del mundo mágico. Después de dos años de guerra constante, Voldemort finalmente obtuvo el control del Ministerio de Magia, y gobernó casi sin enfrentar resistencia, salvo por algunos grupos opositores. A pesar de haber tomado el país, Voldemort seguía insatisfecho, ya que debía eliminar el peligro que la profecía significaba para él. Tras descubrir la ubicación de Potter, Voldemort se aventuró a definitivamente destruir al joven lanzando todas sus fuerzas en un asalto a Hogwarts. Al llegar al colegio, Voldemort enfrentó una rebelión a gran escala compuesta de educadores y estudiantes, así como miembros de la Orden del Fénix y residentes de Hogsmeade. Conforme la batalla se intensificaba, los Mortífagos se vieron obligados a retirarse al Gran Comedor, lugar en el que Voldemort confrontó a Harry Potter en un duelo, y, como todos sus horrocruxes habían sido destruidos, Tom Marvolo Riddle fue finalmente muerto.<br><br>El alma mutilada de Tom Riddle fue confinada en un limbo por toda la eternidad, sin poder moverse o regresar como fantasma.<br><br>Durante toda la saga, a pesar de ser el antagonista principal, se le ha descrito como un personaje ridículo y temeroso de la muerte hasta el extremo, llegando a inspirar, más que miedo, lástima."},
	
	{"nombre":"Bellatrix Lestrange", "actuacion":"Helena Bonham Carter","imagen":"img/personajes/bellatrix.png", "referencia":"personage.html?p=22", "p":"22", 
	"informacion":"Madame Bellatrix Lestrange (de soltera Black) (1951 - 2 de mayo de 1998), también conocida como Bella, fue una bruja de sangre pura, hija de  Cygnus y Druella Black y hermana mayor de Andrómeda y Narcissa. Asistió al Colegio Hogwarts de Magia y Hechicería en 1962 y fue insertada en la casa de Slytherin. Después de Hogwarts, se volvió una Mortífaga fanáticamente leal a Lord Voldemort.<br><br>Bellatrix fue sentenciada a encarcelamiento de por vida en Azkaban por el crimen, pero escapó en la fuga en masa de 1996, junto con otros nueve Mortífagos. Participó en muchas batallas de la Segunda Guerra Mágica, dándose la oportunidad de asesinar a cualquiera de sus parientes miembros de la Orden del Fénix, incluyendo a su primo Sirius Black y a su sobrina Nymphadora Tonks. También mató al elfo doméstico Dobby, y fue la última mortífaga remanente de la Segunda Guerra, durante la última batalla. Molly Weasley acabó la vida de Bellatrix, su violencia y malicia durante la Batalla de Hogwarts."},
	
	{"nombre":"Narcissa Malfoy ", "actuacion":"Helen McCrory","imagen":"img/personajes/Narcissa.jpg", "referencia":"personage.html?p=23", "p":"23", 
	"informacion":"Narcissa Malfoy (de soltera Black; 1955) es una bruja de sangre pura, hermana menor de Andrómeda y Bellatrix, quien afectivamente la llamaba ‘Cissy’. Es esposa del mortífago Lucius Malfoy y madre de Draco. Aunque nunca se declaró oficialmente como mortífaga, Narcissa creía en la importancia de la pureza de la sangre, y estaba a favor de que su marido siguiera a Lord Voldemort durante las Primera y Segunda Guerras Mágicas. Esto, sin embargo, cambió cuando la vida de su hijo se vio en peligro, entre 1996 y 1997.[2] Narcissa hizo todo lo posible por proteger a su familia; incluso mintió a Voldemort sobre la muerte de Harry Potter durante la Batalla de Hogwarts, un acto que salvó a los Malfoy de ser enviados a Azkaban después del fin de la guerra."},
	
	{"nombre":"Lucius Malfoy", "actuacion":"Jason Isaacs","imagen":"img/personajes/lucius.png", "referencia":"personage.html?p=24", "p":"24", 
	"informacion":"Nacido en 1954, es un mago de sangre pura, Hijo de Abraxas Malfoy.<br><br>Era el marido de Narcissa Malfoy (de soltera Black) de la dinastía de los Black (hermana de Bellatrix Lestrange y Andromeda Tonks), y el padre de Draco Malfoy y abuelo de Scorpius Malfoy y viven en la Mansión Malfoy (en Wiltshire). Lucius era un hombre aristocrático, y, además, mortifago, y como tal tenía una obsesión con la pureza de sangre, que presumiblemente adoctrina a su hijo Draco Malfoy con los mismos ideales. Fue fiel a Lord Voldemort, uniendose a los mortífagos y por lo tanto perteneció a los mortífagos y participó en la Primera Guerra Mágica. Después de la primera derrota de Voldemort, Lucius logró evitar que lo encarcelaran difamando que había sido controlado por la Maldición Imperius."},
	
	{"nombre":"Draco Lucius Malfoy ", "actuacion":"Tom Felton","imagen":"img/personajes/draco.png", "referencia":"personage.html?p=25", "p":"25", 
	"informacion":"Es un mago de sangre pura y el único hijo de Lucius y Narcissa Malfoy. Por ser el hijo de un mortífago, a Draco le enseñaron a creer firmemente en la importancia de la pureza de sangre. Asistió al Colegio Hogwarts de Magia y Hechicería desde 1991 hasta 1998 y fue seleccionado en la Casa Slytherin. Durante sus años en Hogwarts, se hizo amigo de Vincent Crabbe, Gregory Goyle, Pansy Parkinson y otros compañeros de Slytherin, mientras él rápidamente desarrolló una rivalidad con Harry Potter. Fue nombrado prefecto de su casa y fue miembro de la Brigada Inquisitorial durante su quinto año, al final del cual fue encarcelado su padre en Azkaban después de la Batalla del Departamento de Misterios. Lord Voldemort se encargó de Draco, con lo que fue un fracaso para Lucius, y se convirtió en un mortífago a la edad de dieciseis años, pero se desilusionó rápidamente con el estilo de vida. Draco no pudo completar su tarea - asesinar a Albus Dumbledore, que fue tomada por Severus Snape - y sólo cumplió con sus deberes por temor y de mala gana. Él y su familia desertaron horas antes del fin de la Segunda Guerra Mágica con el fin de evitar el encarcelamiento en Azkaban después de la derrota de Voldemort. Draco finalmente se casó con Astoria Greengrass y tuvo al menos un hijo, Scorpius Malfoy."},
	
	{"nombre":"Dolores Umbrige", "actuacion":"","imagen":"img/personajes/dolores.png", "referencia":"personage.html?p=26", "p":"26", 
	"informacion":"Madame Subsecretaria Profesora Dolores Jane Umbridge es una mujer de baja estatura y cuerpo rechoncho, generalmente descrita como semejante a un gran sapo, con ojos saltones y cabello corto y rizado de color café. Siempre lleva ropa de color rosa chillón, y feos y exagerados anillos en los dedos. De carácter altivo y arrogante, tiende a interrumpir a la gente cuando habla y a cortarles con un sonoro y particular carraspeo. Su voz es exageradamente aguda, como la de una niña, casi llegando al falsete."}
]